# Generated by Django 4.2.1 on 2023-05-11 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='how_to_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_to_registers', to='pages.howtoregister'),
        ),
    ]
