# Generated by Django 4.2.1 on 2023-05-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_pages_how_to_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.definition'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='how_to_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.howtoregister'),
        ),
    ]
