# Generated by Django 4.2.1 on 2023-05-13 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_pages_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='pages',
            name='extra_cards',
            field=models.ManyToManyField(blank=True, to='pages.cards'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='extra_split_faces',
            field=models.ManyToManyField(blank=True, to='pages.splitface'),
        ),
        migrations.AddField(
            model_name='pages',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category'),
        ),
    ]
