# Generated by Django 4.2.1 on 2023-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_category_alter_pages_extra_cards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='slug',
            field=models.SlugField(blank=True, help_text='if leave it will take from title ', null=True, unique=True),
        ),
    ]
