# Generated by Django 4.2.1 on 2023-05-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_pages_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='each answers',
            new_name='answers',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='each questions',
            new_name='questions',
        ),
    ]
