# Generated by Django 4.2.1 on 2023-05-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_each_answers_faq_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='extra_split_faces',
        ),
        migrations.AddField(
            model_name='pages',
            name='extras',
            field=models.ManyToManyField(blank=True, to='pages.splitface'),
        ),
    ]
