# Generated by Django 4.2.1 on 2023-05-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_pages_extra_split_faces_pages_extras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='extras',
            new_name='extra_split_faces',
        ),
    ]
