# Generated by Django 4.2.1 on 2023-05-16 09:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0010_rename_extras_pages_extra_split_faces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('context', ckeditor.fields.RichTextField()),
                ('date_publish', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text='if leave it will take from title ', null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category')),
            ],
        ),
    ]
