# Generated by Django 4.2.1 on 2023-06-05 16:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='clients')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Mobile_number', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('alternative_number', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Whatsapp_number', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('location_url', models.TextField(blank=True, null=True)),
                ('facebook_url', models.TextField()),
                ('twitter_url', models.TextField(blank=True, null=True)),
                ('instagram_url', models.TextField()),
                ('linkedin_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('client_name', models.TextField(help_text='use | for next line')),
                ('client_position', models.TextField()),
                ('client_reviews', models.TextField(help_text='use | for next line . Only 6 lines allowed')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='use | for next line')),
                ('description', models.TextField(help_text='use | for next line . Only 4 lines allowed')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts_title', models.TextField()),
                ('counts_number', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='workshostory')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aboutus')),
                ('clients', models.ManyToManyField(to='home.client')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cover')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.testimonial')),
                ('why_choose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.whychoose')),
                ('work_history', models.ManyToManyField(to='home.workhistory')),
            ],
        ),
    ]
